name: Generate RSS and Sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate robots.txt
        run: node tools/generate-robots.js

      - name: Commit and Push robots.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add rss.xml sitemap.xml robots.txt || true
          git commit -m "Update generated files" || echo "No changes"
          git pull --rebase --autostash origin main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
